### ISSUE TITLE
Почему при добавлении в id ненулевые цифры?

### ISSUE THREAD

**Issue by coursar** [sergey-lb/ozon#6]
https://ozon-project.herokuapp.com/books/00000000-0000-4000-8000-000000000000/edit

**Comment by sergey-lb** [comment]
Честно сказать, не разобрался как получить UUID со всеми нулями?

**Comment by coursar** [comment]
а вы как его создаёте?

```python
import uuid
uuid.UUID(int=0)  # будет UUID('00000000-0000-0000-0000-000000000000')
```
